<?php

$body = <<<'BODY'
# DIRECTIVE: directive-learn

Capitalise the technical decisions from the completed change into the project's spec files:
`directive-spec/config.yaml` (project-level rules) and `directive-spec/context/<tech>.yaml`
(tech-specific rules). Follow these steps exactly.

## Input

Optionally specify a change name. If omitted, inferred from context.

## Steps

### Step 1 — Read the change artifacts

Read all available artifacts for the change:
- `proposal.md`
- `design.md`
- `specs/**/*.md`
- `tasks.md`
- `reflect.md` (if present)

### Step 2 — Extract reapplicable technical decisions

From the artifacts, extract **every** technical decision that is reapplicable to future changes
in this project. There is no limit on the number of rules — exhaustiveness is the goal.

A decision is reapplicable if it answers "Would I want the agent to remember this for the next
change?" If yes, it must be proposed.

Classify each extracted decision as either:
- **project-level** → goes into `directive-spec/config.yaml`
  (e.g. architecture patterns, naming conventions, cross-cutting standards)
- **tech-specific** → goes into `directive-spec/context/<tech>.yaml`
  (e.g. PHP type hints rules, YAML formatting, CSS class conventions)

Ignore one-shot decisions and ad hoc implementation details that have no chance of recurring.

### Step 3 — Identify the techs concerned

From the extracted tech-specific decisions, infer the technology names (lowercase kebab-case,
e.g. `php`, `typescript`, `css`).

If the inferred tech list is ambiguous, ask the user to confirm before proceeding:
> "I identified the following technologies from this change: [list]. Does that look right?"

### Step 4 — Present proposed modifications

For each target file, show the user the exact new entries to be added:

```
## Proposed additions to directive-spec/config.yaml

- <rule 1>
- <rule 2>

## Proposed additions to directive-spec/context/php.yaml

conventions:
  - <rule A>
  - <rule B>
```

Then ask:
> "Do these look right? You can remove or adjust any entries before I write them.
> Reply with corrections, or confirm to proceed."

Wait for explicit confirmation. Do not write anything before the user confirms.

### Step 5 — Write non-destructively

For each file:

**`directive-spec/config.yaml`** — read the existing file, append the confirmed project-level
rules into the appropriate sections. Never remove or modify existing entries.

**`directive-spec/context/<tech>.yaml`** — read the existing file and add the confirmed
tech-specific rules. If the file does not exist, create it with the same structure that
`directive-stack` would produce:

```yaml
# Stack rules for <tech> — generated by directive-learn
conventions:
  - <rule A>
  - <rule B>
```

Then register `<tech>.yaml` in `directive-spec/context/common.yaml` (under `context.stack_files`)
if not already listed.

When done, inform the user:
> "Capitalisation complete. Rules written to:
> - directive-spec/config.yaml
> - directive-spec/context/<tech>.yaml
>
> Invoke `directive-archive` to finalise the change."

## Output

```
## Capitalisation Complete

**Change:** <change-name>

**Files updated:**
- directive-spec/config.yaml (+N rules)
- directive-spec/context/<tech>.yaml (+M rules)

Invoke `directive-archive` to finalise the change.
```

## Guardrails

- Do NOT write anything before the user has confirmed the proposed additions (Step 4)
- Do NOT remove or modify existing entries in any file — only append
- Do NOT reference or create `lessons-learned.md`
- Create `context/<tech>.yaml` if absent, using the structure from `directive-stack`
- Register new `<tech>.yaml` files in `common.yaml` if not already listed
- All tech names MUST be lowercase kebab-case
BODY;
return ['description' => 'Capitalise technical decisions from the change into spec context files', 'body' => $body];
