<?php

$body = <<<'BODY'
# DIRECTIVE: directive-stack

Learn the technical stack of this project and record the rules in
`directive-spec/context/<tech>.yaml`. Follow these steps exactly.

## Input

No argument required. Optionally accepts `<tech>` to target a specific language or framework.

## Steps

### Step 1 — Ask for hints

Ask the user:
> "Which directory should I focus on? Are there any documentation files, READMEs, or conventions I
> should read to better understand the stack? (Optional — press Enter to skip)"

Wait for the answer. Note any paths or files the user mentions.

### Step 2 — Analyse the repository

Read the following files if they exist:
- `composer.json` (PHP dependencies, autoload namespace)
- `package.json` (Node.js dependencies)
- `phpstan.neon` or `phpstan.neon.dist` (static analysis config)
- `.php-cs-fixer.php` or `.php-cs-fixer.dist.php` (code style config)
- `tsconfig.json` (TypeScript config)
- Any files mentioned by the user in Step 1

Also scan the top-level directory structure to identify the main source folders, test folders,
and config files.

### Step 3 — Infer the stack

From the files read in Step 2, infer:
- **Language** and version constraint (e.g., PHP ^8.4, Node.js 20)
- **Frameworks** (e.g., Slim 4, Symfony 7, React 18)
- **Testing** framework and conventions (e.g., Pest 3, PHPUnit, Jest, Vitest)
- **Conventions**: phpstan level, code style tool, namespace root, DI container
- **Architecture patterns** (e.g., hexagonal, MVC, CQRS, modular monolith)

Normalise the `<tech>` name to **lowercase kebab-case** (e.g., `PHP` → `php`, `TypeScript` → `typescript`).

### Step 4 — Confirm ambiguities

Present the full inferred result to the user:
> "Here is what I inferred for the `<tech>` stack:
> [... show the structured values ...]
> Does this look correct? Any corrections?"

For each value that is uncertain or missing, ask a targeted yes/no or short-answer question.
Wait for the user's confirmation or corrections before proceeding.

### Step 5 — Write directive-spec/context/<tech>.yaml

If `directive-spec/context/<tech>.yaml` already exists:
- Show the existing content
- Ask: "This file already exists. Should I overwrite it with the new values?"
- Proceed only if the user confirms

Create or overwrite `directive-spec/context/<tech>.yaml` with this structure:

```yaml
# Stack rules for <tech> — generated by directive-stack
language:
  name: <language>
  version: <version constraint>
frameworks:
  - name: <framework>
    version: <version or description>
testing:
  framework: <test runner>
  conventions: <notes>
conventions:
  phpstan_level: <N>
  code_style: <tool and config notes>
  namespace_root: <root namespace>
patterns:
  - <architectural pattern or rule>
```

Omit sections that do not apply (e.g., `phpstan_level` for a JavaScript project).

### Step 6 — Update common.yaml

Open `directive-spec/context/common.yaml` and add `<tech>.yaml` to the `context.stack_files` list.

Rules:
- Do NOT remove any existing entries
- Do NOT add a duplicate if `<tech>.yaml` is already listed
- Use 2-space indentation

Example result:
```yaml
context:
  stack_files:
    - php.yaml
    - typescript.yaml
```

When done, inform the user:
> "Stack rules saved to `directive-spec/context/<tech>.yaml` and registered in `common.yaml`.
> Invoke `directive-new <change-name>` to start a change — the stack rules will be used in artifact instructions."

## Output

```
## Stack rules saved

**File:** directive-spec/context/<tech>.yaml
**Registered in:** directive-spec/context/common.yaml

Invoke `directive-new <change-name>` to start a change.
```

## Guardrails

- Always confirm ambiguous inferences with the user before writing the file
- Normalise tech name to lowercase kebab-case
- Ask confirmation before overwriting an existing `<tech>.yaml`
- Do NOT add duplicate entries to `common.yaml`
- Use 2-space indentation throughout
BODY;
return ['description' => 'Set up stack rules', 'body' => $body];
